name: Deploy in Okteto

on:
  workflow_dispatch:

jobs:
  deploy_in_okteto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests
        run: mvn test
      - name: Create tag
        run: echo "tag=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)" >> $GITHUB_OUTPUT
        id: project
      - name: Generate Docker image
        run: mvn spring-boot:build-image.imageName=${{ secrets.DOCKERHUB_USERNAME }}/okteto-anuncios:${{ steps.project.outputs.tag }} -DskipTests
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/okteto-anuncios:${{ steps.project.outputs.tag }}
      - name: Install Okteto CLI
        run: curl https://get.okteto.com -sSfL | sh
      - name: Login into Okteto
        run: okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
      - name: Deploy to Okteto
        run: okteto deploy --wait
